[theme]

# Primary accent for interactive elements
primaryColor = '#09ab3c'

# Background color for the main content area
backgroundColor = '#263647'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#858585'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
